apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bikerent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Pratiks-96/ps-bike-rentals.git
    targetRevision: main
    path: helm/frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: bikerent   # 👈 add your app namespace here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
